import mongoose from "mongoose";

const panelSchema = new mongoose.Schema(
  {
    panelId: { type: String, required: true, unique: true, trim: true },
    panelName: { type: String, required: true, trim: true },
    panelType: { type: String, default: "MCC" },
    manufacturingDate: { type: String, default: "" },
    installationDate: { type: String, default: "" },
    company: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Company",
      required: true,
    },
    companyId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Company",
      required: true,
      index: true,
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
    customer: { type: String, default: "" },
    installer: { type: String, default: "" },
    manufacturer: { type: String, default: "" },
    installationLocation: { type: String, default: "" },
    projectName: { type: String, default: "" },
    description: { type: String, default: "" },
    motorConfiguration: {
      type: [
        {
          connectionType: { type: String, default: "DOL" },
          minHp: { type: String, default: "5" },
          maxHp: { type: String, default: "15" },
        },
      ],
      default: [],
    },
    technicalSpecs: {
      voltage: { type: String, default: "" },
      current: { type: String, default: "" },
      frequency: { type: String, default: "" },
      phase: { type: String, default: "" },
      powerRating: { type: String, default: "" },
      powerFactor: { type: String, default: "" },
      mccb: { type: String, default: "" },
      mcb: { type: String, default: "" },
      tpBreaker: { type: String, default: "" },
      spBreaker: { type: String, default: "" },
      fuseRating: { type: String, default: "" },
      plc: { type: String, default: "" },
      hmi: { type: String, default: "" },
      relay: { type: String, default: "" },
      contactor: { type: String, default: "" },
      vfd: { type: String, default: "" },
      softStarter: { type: String, default: "" },
      timer: { type: String, default: "" },
      overloadRelay: { type: String, default: "" },
      digitalMeter: { type: String, default: "" },
      cableDuct: { type: String, default: "" },
      terminalBlock: { type: String, default: "" },
      autoManualSelectorSwitch: { type: String, default: "" },
      smps: { type: String, default: "" },
      controlTransformer: { type: String, default: "" },
      startPushButton: { type: String, default: "" },
      stopPushButton: { type: String, default: "" },
      emergencyStop: { type: String, default: "" },
      selectorSwitch: { type: String, default: "" },
      indicatorLamps: { type: String, default: "" },
      busbarRating: { type: String, default: "" },
      busbarMaterial: { type: String, default: "" },
      cableSize: { type: String, default: "" },
      controlCableSize: { type: String, default: "" },
      overCurrentProtection: { type: Boolean, default: false },
      shortCircuitProtection: { type: Boolean, default: false },
      earthFaultProtection: { type: Boolean, default: false },
      phaseFailureProtection: { type: Boolean, default: false },
      overVoltageProtection: { type: Boolean, default: false },
      underVoltageProtection: { type: Boolean, default: false },
      dryRunProtection: { type: Boolean, default: false },
      overloadProtection: { type: Boolean, default: false },
      controlVoltage: { type: String, default: "" },
      instrumentQuantities: { type: mongoose.Schema.Types.Mixed, default: {} },
      protectionType: { type: String, default: "" },
      ipRating: { type: String, default: "" },
      enclosureMaterial: { type: String, default: "" },
      panelColor: { type: String, default: "" },
      dimensions: { type: String, default: "" },
      weight: { type: String, default: "" },
      mountingType: { type: String, default: "" },
      drawingNumber: { type: String, default: "" },
      revision: { type: String, default: "" },
    },
    images: {
      frontImage: { type: String, default: "" },
      insideImage: { type: String, default: "" },
      namePlateImage: { type: String, default: "" },
      sideImage: { type: String, default: "" },
    },
    diagrams: {
      type: [
        {
          name: { type: String, default: "" },
          url: { type: String, default: "" },
          publicId: { type: String, default: "" },
          fileType: { type: String, default: "" },
          source: {
            type: String,
            enum: ["upload", "library"],
            default: "upload",
          },
          libraryId: { type: String, default: "" },
        },
      ],
      default: [],
      validate: {
        validator: (value) => Array.isArray(value) && value.length <= 5,
        message: "A panel can have at most 5 wiring diagrams.",
      },
    },
    instrumentModels: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },
    // Placeholder fields for future AI wiring and connection modules
    wiring: {
      libraryRef: { type: String, default: "" },
      aiGenerated: { type: Boolean, default: false },
      artifacts: { type: [String], default: [] },
      notes: { type: String, default: "" },
    },
    connections: {
      terminals: { type: [Object], default: [] },
      notes: { type: String, default: "" },
    },
    qrUrl: { type: String, default: "" },
    qrCodeUrl: { type: String, default: "" },
    publicPanelUrl: { type: String, default: "" },
    qrGeneratedAt: { type: Date },
    status: {
      type: String,
      enum: [
        "Draft",
        "Installed",
        "Pending",
        "In Production",
        "QC Review",
        "Maintenance Due",
      ],
      default: "Draft",
    },
    qrGenerated: { type: Boolean, default: false },
  },
  { timestamps: true },
);

panelSchema.index({ company: 1, panelType: 1, createdAt: -1 });

export default mongoose.model("Panel", panelSchema);
